# Generated by Django 3.0.1 on 2020-01-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_coin", models.CharField(max_length=100)),
                ("amount_holding", models.CharField(max_length=100)),
            ],
        ),
    ]
