# Generated by Django 3.0.1 on 2020-01-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_remove_coin_amount_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='amount_holding',
            field=models.IntegerField(default=0),
        ),
    ]
