# Generated by Django 3.0.1 on 2020-02-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("display", "0004_coin_amount_holding"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="display.Portfolio",
            ),
            preserve_default=False,
        ),
    ]
